export const DiamondColors = [
  { id: 1, img: 'yellow', name: 'Yellow', value: 'Yellow' },
  {
    id: 2,
    img: 'greenish-yellow',
    name: 'Green/ish Yellow',
    value: 'Greenish Yellow',
  },
  {
    id: 3,
    img: 'orange-yellow',
    name: 'Orange Yellow',
    value: 'Orange Yellow',
  },
  {
    id: 3,
    img: 'orangy-yellow',
    name: 'Orangy Yellow',
    value: 'Orangy Yellow',
  },
  {
    id: 4,
    img: 'pink',
    name: 'Pink/Purple/ish Pink',
    value: 'Pink - Purplish Pink',
  },
  {
    id: 4,
    img: 'pink',
    name: 'Pink/Purple/ish Pink',
    value: 'Pink',
  },
  {
    id: 4,
    img: 'pink',
    name: 'Pink/Purple/ish Pink',
    value: 'Purplish Pink',
  },
  { id: 5, img: 'orangy-pink', name: 'Orangy Pink', value: 'Orangy Pink' },
  {
    id: 7,
    img: 'pinkish-purple',
    name: 'Pink/ish Purple',
    value: 'Pinkish Purple',
  },
  { id: 8, img: 'purple', name: 'Purple', value: 'Purple' },
  {
    id: 9,
    img: 'brownish-pink',
    name: 'Brownish Pink',
    value: 'Brownish Pink',
  },
  { id: 10, img: 'brown-pink', name: 'Brown Pink', value: 'Brown Pink' },
  { id: 11, img: 'blue', name: 'Blue', value: 'Blue' },
  { id: 12, img: 'grey-blue', name: 'Gray Blue', value: 'Gray Blue' },
  { id: 13, img: 'green-blue', name: 'Green Blue', value: 'Green Blue' },
  {
    id: 13,
    img: 'greenish-blue',
    name: 'Greenish Blue',
    value: 'Greenish Blue',
  },
  { id: 14, img: 'grayish-blue', name: 'Grayish Blue', value: 'Grayish Blue' },
  { id: 15, img: 'orange', name: 'Orange', value: 'Orange' },
  {
    id: 16,
    img: 'yellow-orange',
    name: 'Yellow Orange',
    value: 'Yellow Orange',
  },
  {
    id: 17,
    img: 'yellowish-orange',
    name: 'Yellowish Orange',
    value: 'Yellowish Orange',
  },
  { id: 18, img: 'brown-orange', name: 'Brown Orange', value: 'Brown Orange' },
  { id: 19, img: 'green', name: 'Green', value: 'Green' },
  {
    id: 20,
    img: 'yellow-green',
    name: 'Yellow/ish Green',
    value: 'Yellow Green',
  },
  {
    id: 20,
    img: 'yellow-green',
    name: 'Yellow/ish Green',
    value: 'Yellowish Green',
  },
  {
    id: 20,
    img: 'yellow-green',
    name: 'Green/ish Yellow',
    value: 'Green Yellow',
  },
  {
    id: 21,
    img: 'bluegreen',
    name: 'Blue Green',
    value: 'Blue Green',
  },
  {
    id: 22,
    img: 'bluish-green',
    name: 'Bluish Green',
    value: 'Bluish Green',
  },
  { id: 23, img: 'red', name: 'Red', value: 'Red' },
  { id: 24, img: 'purplish-red', name: 'Purplish Red', value: 'Purplish Red' },
  { id: 25, img: 'grey', name: 'Gray', value: 'Gray' },
  { id: 26, img: 'blue-grey', name: 'Blue/ish Gray', value: 'Blue Gray' },
  {
    id: 27,
    img: 'bluegreen',
    name: 'Blue/ish Gray',
    value: 'Blueish Gray',
  },
  {
    id: 28,
    img: 'bluegreen',
    name: 'Blue/ish Gray',
    value: 'Bluish Gray',
  },
  {
    id: 30,
    img: 'pink',
    name: 'Pink/Purple/ish Pink',
    value: 'Purple Pink',
  },
  {
    id: 30,
    img: 'Pinkish-Purple',
    name: 'Pink/ish Purple',
    value: 'Pinkish Purple',
  },
  {
    id: 30,
    img: 'Pinkish-Purple',
    name: 'Pink/ish Purple',
    value: 'Pink Purple',
  },
  {
    id: 30,
    img: 'Pinkish-Purple',
    name: 'Pink/ish Purple',
    value: 'Pink Purple',
  },
  {
    id: 30,
    img: 'Pinkish-Purple',
    name: 'Pink/ish Purple',
    value: 'Pinkish-Purple',
  },
  {
    id: 30,
    img: 'Pinkish-Purple',
    name: 'Pink/ish Purple',
    value: 'Pink-Purple',
  },
  {
    id: 31,
    img: 'brownish-orange',
    name: 'Brownish Orange',
    value: 'Brownish Orange',
  },
  {
    id: 32,
    img: 'gray-violet',
    name: 'Gray/ish Violet',
    value: 'Grayish Violet',
  },
    {
    id: 32,
    img: 'gray-violet',
    name: 'Gray/ish Violet',
    value: 'Gray Violet',
  },
  
  {
    id: 33,
    img: 'brownish-yellowish-orange',
    name: 'Brownish Yellowish Orange',
    value: 'Brownish Yellowish Orange',
  },
  {
    id: 33,
    img: 'brownish-orangy-pink',
    name: 'Brownish Orange/y Pink',
    value: 'Brownish Orangy Pink',
  },
  {
    id: 33,
    img: 'brownish-orangy-pink',
    name: 'Brownish Orange/y Pink',
    value: 'Brownish Orange Pink',
  },
  {
    id: 33,
    img: 'brownish-orangy-pink',
    name: 'Brownish Orange/y Pink',
    value: 'Brownish Orange/y Pink',
  },
  {
    id: 35,
    img: 'pinkish-orange',
    name: 'Pink/ish Orange',
    value: 'Pinkish Orange',
  },
  {
    id: 35,
    img: 'pinkish-orange',
    name: 'Pink/ish Orange',
    value: 'Pink Orange',
  },
    {
    id: 35,
    img: 'brownish-yellow',
    name: 'Brown/ish Yellow',
    value: 'Brown/ish Yellow',
  },
    {
    id: 35,
    img: 'brownish-yellow',
    name: 'Brown/ish Yellow',
    value: 'Brown Yellow',
  }
];

export const DiaryDiamondColors = [
  { id: 1, img: 'yellow', name: 'Yellow', value: 'Yellow' },
  {
    id: 2,
    img: 'greenish-yellow',
    name: 'Greenish Yellow',
    value: 'Greenish Yellow',
  },
  {
    id: 2,
    img: 'greenish-yellow',
    name: 'Greenish Yellow',
    value: 'Green Yellow',
  },
  {
    id: 3,
    img: 'orange-yellow',
    name: 'Orange Yellow',
    value: 'Orange Yellow',
  },
  {
    id: 4,
    img: 'pink',
    name: 'Pink',
    value: 'Pink',
  },
  { id: 5, img: 'orangy-pink', name: 'Orangy Pink', value: 'Orangy Pink' },
  {
    id: 6,
    img: 'purplish-pink',
    name: 'Purplish Pink',
    value: 'Purplish Pink',
  },
  {
    id: 7,
    img: 'pinkish-purple',
    name: 'Pink/ish Purple',
    value: 'Pink/ish Purple',
  },
  { id: 8, img: 'purple', name: 'Purple', value: 'Purple' },
  { id: 8, img: 'pink', name: 'Purple Pink', value: 'Purple Pink' },
  {
    id: 9,
    img: 'brownish-pink',
    name: 'Brownish Pink',
    value: 'Brownish Pink',
  },
  { id: 10, img: 'brown-pink', name: 'Brown Pink', value: 'Brown Pink' },
  { id: 11, img: 'blue', name: 'Blue', value: 'Blue' },
  { id: 12, img: 'grey-blue', name: 'Gray Blue', value: 'Gray Blue' },
  { id: 13, img: 'green-blue', name: 'Green Blue', value: 'Green Blue' },
  {
    id: 14,
    img: 'greenish-blue',
    name: 'Greenish Blue',
    value: 'Greenish Blue',
  },
  { id: 15, img: 'grayish-blue', name: 'Grayish Blue', value: 'Grayish Blue' },
  { id: 16, img: 'orange', name: 'Orange', value: 'Orange' },
  {
    id: 17,
    img: 'yellow-orange',
    name: 'Yellow Orange',
    value: 'Yellow Orange',
  },
  {
    id: 18,
    img: 'yellowish-orange',
    name: 'Yellowish Orange',
    value: 'Yellowish Orange',
  },
  { id: 19, img: 'brown-orange', name: 'Brown Orange', value: 'Brown Orange' },
  { id: 20, img: 'green', name: 'Green', value: 'Green' },
  {
    id: 21,
    img: 'yellow-green',
    name: 'Yellow Green',
    value: 'Yellow Green',
  },
  {
    id: 22,
    img: 'bluegreen',
    name: 'Blue Green',
    value: 'Blue Green',
  },
  {
    id: 23,
    img: 'bluish-green',
    name: 'Bluish Green',
    value: 'Bluish Green',
  },
  { id: 24, img: 'red', name: 'Red', value: 'Red' },
  { id: 25, img: 'purplish-red', name: 'Purplish Red', value: 'Purplish Red' },
  { id: 26, img: 'grey', name: 'Gray', value: 'Gray' },
  { id: 27, img: 'blue-grey', name: 'Blue Gray', value: 'Blue Gray' },

  { id: 27, img: 'purple-brown-grey', value: 'Purple with Brown or Gray' },
  { id: 28, img: 'grey-violet', value: 'Gray-violet - violet gray' },
  { id: 29, img: 'violet-blue', value: 'Violet-blue to blue violet' },
  { id: 30, img: 'violet', value: 'Violet' },
  { id: 31, img: 'greyish-yellow-green', value: 'Grayish yellow-green' },
  {
    id: 32,
    img: 'brownish-greenish-yellow',
    value: 'Brownish greenish yellow',
  },
  { id: 33, img: 'greyish-green-yellow', value: 'Grayish green-yellow' },
  { id: 34, img: 'green-grey', value: 'Green gray to gray green' },
  {
    id: 35,
    img: 'greenish-yellow',
    name: 'Green/ish Yellow',
    value: 'Green/ish Yellow',
  },
  {
    id: 36,
    img: 'purplish-pink',
    name: 'Purple/ish Pink',
    value: 'Purple/ish Pink',
  },
  {
    id: 37,
    img: 'purplish-pink',
    name: 'Pink - Purplish Pink',
    value: 'Pink - Purplish Pink',
  },
  {
    id: 38,
    img: 'yellow-green',
    name: 'Yellow/ish Green',
    value: 'Yellow/ish Green',
  },
  { id: 39, img: 'blue-grey', name: 'Blue/ish Gray', value: 'Blue/ish Gray' },
  {
    id: 40,
    img: 'pink',
    name: 'Pink/Purple/ish Pink',
    value: 'Pink/Purple/ish Pink',
  },
  {
    id: 41,
    img: 'orangy-yellow',
    name: 'Orangy Yellow',
    value: 'Orangy Yellow',
  },
  {
    id: 42,
    img: 'pink',
    name: 'Pink/ish Purple',
    value: 'Pink/ish Purple',
  },
  {
    id: 43,
    img: 'brownish-orange',
    name: 'Brownish Orange',
    value: 'Brownish Orange',
  },
  {
    id: 44,
    img: "gray-violet",
    name: "Gray/ish Violet",
    value: "Gray Violet",
  },
   {
    id: 44,
    img: "gray-violet",
    name: "Gray/ish Violet",
    value: "Grayish Violet",
  },
   {
    id: 45,
    img: "brownish-yellowish-orange",
    name: "Brownish Yellowish Orange",
    value: "Brownish Yellowish Orange",
  },{
    id: 32,
    img: 'brownish-orangy-pink',
    name: 'Brownish Orange/y Pink',
    value: 'Brownish Orangy Pink',
  },
  {
    id: 33,
    img: 'brownish-orangy-pink',
    name: 'Brownish Orange/y Pink',
    value: 'Brownish Orange Pink',
  },
  {
    id: 33,
    img: 'brownish-orangy-pink',
    name: 'Brownish Orange/y Pink',
    value: 'Brownish Orange Pink',
  },
  {
    id: 32,
    img: 'brownish-orangy-pink',
    name: 'Brownish Orangy Pink',
    value: 'Brownish Orange/y Pink',
  },
  {
    id: 37,
    img: 'pinkish-orange',
    name: 'Pink/ish Orange',
    value: 'Pink/ish Orange',
  },
   {
    id: 38,
    img: 'brownish-yellow',
    name: 'Brown/ish Yellow',
    value: 'Brown/ish Yellow',
  },
   {
    id: 38,
    img: 'brownish-yellow',
    name: 'Brown/ish Yellow',
    value: 'Brown Yellow',
  }
];

export const ArgyleDiamonds = [
  {
    color: { img: "pink", value: "Pink" },
    shape: [
      { id: 1, img: "radient", value: "Radiant" },
      { id: 2, img: "cushion", value: "Cushion" },
      { id: 3, img: "oval", value: "Oval" },
      { id: 4, img: "heart", value: "Heart" },
      { id: 5, img: "pear", value: "Pear" },
      { id: 6, img: "emerald", value: "Emerald" },
      { id: 7, img: "round", value: "Round" },
      { id: 8, img: "marquise", value: "Marquise" },
      { id: 9, img: "hexagon", value: "Hexagon" },
      { id: 10, img: "triangular-brilliant", value: "Triangular Brilliant" },
      { id: 11, img: "octagon", value: "Octagon" },
      { id: 12, img: "princess", value: "Princess" },
      { id: 13, img: "trilliant", value: "Trilliant" },
      { id: 14, img: "kite", value: "Kite" },
      { id: 15, img: "shield", value: "Shield" },
    ],
    saturation: [
      "Fancy",
      "Fancy Intense",
      "Fancy Vivid",
      "Fancy Deep",
    ],
    clarity: [
      { diamondType: ["FL or IF"], value: "IF", desc: "Flawless/Internally…" },
      { diamondType: ["VVS"], value: "VVS", desc: "Very Very Slightly Incl…" },
      { diamondType: ["VS"], value: "VS", desc: "Very  Slightly Inclusion" },
      { diamondType: ["SI1"], value: "SI1", desc: "Slightly Inclusion" },
      { diamondType: ["SI2"], value: "SI2", desc: "Slightly Inclusion" },
      { diamondType: ["I1"], value: "I1", desc: "Inclusion or Pique" },
      { diamondType: ["I2"], value: "I2", desc: "Inclusion or Pique" },
      { diamondType: ["I3"], value: "I3", desc: "Inclusion or Pique" },
    ],
  },
  {
    color: { img: "purplish-pink", value: "Purplish Pink" },
    shape: [
      { id: 1, img: "radient", value: "Radiant" },
      { id: 2, img: "cushion", value: "Cushion" },
      { id: 3, img: "oval", value: "Oval" },
      { id: 4, img: "heart", value: "Heart" },
      { id: 5, img: "pear", value: "Pear" },
      { id: 6, img: "emerald", value: "Emerald" },
      { id: 7, img: "round", value: "Round" },
      { id: 8, img: "marquise", value: "Marquise" },
    ],
    saturation: [
      "Fancy",
      "Fancy Intense",
      "Fancy Vivid",
      "Fancy Deep",
    ],
    clarity: [
      { diamondType: ["FL or IF"], value: "IF", desc: "Flawless/Internally…" },
      { diamondType: ["VVS"], value: "VVS", desc: "Very Very Slightly Incl…" },
      { diamondType: ["VS"], value: "VS", desc: "Very  Slightly Inclusion" },
      { diamondType: ["SI1"], value: "SI1", desc: "Slightly Inclusion" },
      { diamondType: ["SI2"], value: "SI2", desc: "Slightly Inclusion" },
      { diamondType: ["I1"], value: "I1", desc: "Inclusion or Pique" },
      { diamondType: ["I2"], value: "I2", desc: "Inclusion or Pique" },
      { diamondType: ["I3"], value: "I3", desc: "Inclusion or Pique" },
    ],
  },
  {
    color: { img: "purple-pink", value: "Purple Pink" },
    shape: [
      { id: 1, img: "radient", value: "Radiant" },
      { id: 2, img: "cushion", value: "Cushion" },
      { id: 3, img: "oval", value: "Oval" },
      { id: 4, img: "heart", value: "Heart" },
      { id: 5, img: "pear", value: "Pear" },
      { id: 6, img: "emerald", value: "Emerald" },
      { id: 7, img: "round", value: "Round" },
      { id: 8, img: "marquise", value: "Marquise" },
      { id: 9, img: "hexagon", value: "Hexagon" },
      { id: 10, img: "triangular-brilliant", value: "Triangular Brilliant" },
      { id: 11, img: "octagon", value: "Octagon" },
      { id: 12, img: "princess", value: "Princess" },
      { id: 13, img: "trilliant", value: "Trilliant" },
      { id: 14, img: "kite", value: "Kite" },
      { id: 15, img: "shield", value: "Shield" },
    ],
    saturation: [
      "Fancy",
      "Fancy Intense",
      "Fancy Vivid",
      "Fancy Deep",
    ],
    clarity: [
      { diamondType: ["FL or IF"], value: "IF", desc: "Flawless/Internally…" },
      { diamondType: ["VVS"], value: "VVS", desc: "Very Very Slightly Incl…" },
      { diamondType: ["VS"], value: "VS", desc: "Very  Slightly Inclusion" },
      { diamondType: ["SI1"], value: "SI1", desc: "Slightly Inclusion" },
      { diamondType: ["SI2"], value: "SI2", desc: "Slightly Inclusion" },
      { diamondType: ["I1"], value: "I1", desc: "Inclusion or Pique" },
      { diamondType: ["I2"], value: "I2", desc: "Inclusion or Pique" },
      { diamondType: ["I3"], value: "I3", desc: "Inclusion or Pique" },
    ],
  },
  {
    color: { img: "brwonish-orangy-pink", value: "Brownish Orangy Pink" },
    shape: [
      { id: 1, img: "radient", value: "Radiant" },
      { id: 2, img: "cushion", value: "Cushion" },
      { id: 3, img: "oval", value: "Oval" },
      { id: 4, img: "heart", value: "Heart" },
      { id: 5, img: "pear", value: "Pear" },
      { id: 6, img: "emerald", value: "Emerald" },
      { id: 7, img: "round", value: "Round" },
      { id: 8, img: "marquise", value: "Marquise" },
      { id: 9, img: "hexagon", value: "Hexagon" },
      { id: 10, img: "triangular-brilliant", value: "Triangular Brilliant" },
      { id: 11, img: "octagon", value: "Octagon" },
      { id: 12, img: "princess", value: "Princess" },
      { id: 13, img: "trilliant", value: "Trilliant" },
      { id: 14, img: "kite", value: "Kite" },
      { id: 15, img: "shield", value: "Shield" },
    ],
    saturation: [
      "Fancy",
      "Fancy Intense",
      "Fancy Vivid",
      "Fancy Deep",
    ],
    clarity: [
      { diamondType: ["FL or IF"], value: "IF", desc: "Flawless/Internally…" },
      { diamondType: ["VVS"], value: "VVS", desc: "Very Very Slightly Incl…" },
      { diamondType: ["VS"], value: "VS", desc: "Very  Slightly Inclusion" },
      { diamondType: ["SI1"], value: "SI1", desc: "Slightly Inclusion" },
      { diamondType: ["SI2"], value: "SI2", desc: "Slightly Inclusion" },
      { diamondType: ["I1"], value: "I1", desc: "Inclusion or Pique" },
      { diamondType: ["I2"], value: "I2", desc: "Inclusion or Pique" },
      { diamondType: ["I3"], value: "I3", desc: "Inclusion or Pique" },
    ],
  },
  {
    color: { img: "pink-purple", value: "Pink Purple" },
    shape: [
      { id: 1, img: "radient", value: "Radiant" },
      { id: 2, img: "cushion", value: "Cushion" },
      { id: 3, img: "oval", value: "Oval" },
      { id: 4, img: "heart", value: "Heart" },
      { id: 5, img: "pear", value: "Pear" },
      { id: 6, img: "emerald", value: "Emerald" },
      { id: 7, img: "round", value: "Round" },
      { id: 8, img: "marquise", value: "Marquise" },
      { id: 9, img: "hexagon", value: "Hexagon" },
      { id: 10, img: "triangular-brilliant", value: "Triangular Brilliant" },
      { id: 11, img: "octagon", value: "Octagon" },
      { id: 12, img: "princess", value: "Princess" },
      { id: 13, img: "trilliant", value: "Trilliant" },
      { id: 14, img: "kite", value: "Kite" },
      { id: 15, img: "shield", value: "Shield" },
    ],
    saturation: [
      "Fancy",
      "Fancy Intense",
      "Fancy Vivid",
      "Fancy Deep",
    ],
    clarity: [
      { diamondType: ["FL or IF"], value: "IF", desc: "Flawless/Internally…" },
      { diamondType: ["VVS"], value: "VVS", desc: "Very Very Slightly Incl…" },
      { diamondType: ["VS"], value: "VS", desc: "Very  Slightly Inclusion" },
      { diamondType: ["SI1"], value: "SI1", desc: "Slightly Inclusion" },
      { diamondType: ["SI2"], value: "SI2", desc: "Slightly Inclusion" },
      { diamondType: ["I1"], value: "I1", desc: "Inclusion or Pique" },
      { diamondType: ["I2"], value: "I2", desc: "Inclusion or Pique" },
      { diamondType: ["I3"], value: "I3", desc: "Inclusion or Pique" },
    ],
  },
  {
    color: { img: "red", value: "Red" },
    shape: [
      { id: 1, img: "radient", value: "Radiant" },
      { id: 2, img: "cushion", value: "Cushion" },
      { id: 3, img: "oval", value: "Oval" },
      { id: 4, img: "heart", value: "Heart" },
      { id: 5, img: "pear", value: "Pear" },
      { id: 6, img: "emerald", value: "Emerald" },
      { id: 7, img: "round", value: "Round" },
      { id: 8, img: "marquise", value: "Marquise" },
      { id: 9, img: "hexagon", value: "Hexagon" },
      { id: 10, img: "triangular-brilliant", value: "Triangular Brilliant" },
      { id: 11, img: "octagon", value: "Octagon" },
      { id: 12, img: "princess", value: "Princess" },
      { id: 13, img: "trilliant", value: "Trilliant" },
      { id: 14, img: "kite", value: "Kite" },
      { id: 15, img: "shield", value: "Shield" },
    ],
    saturation: [
      "Fancy",
    ],
    clarity: [
      { diamondType: ["FL or IF"], value: "IF", desc: "Flawless/Internally…" },
      { diamondType: ["VVS"], value: "VVS", desc: "Very Very Slightly Incl…" },
      { diamondType: ["VS"], value: "VS", desc: "Very  Slightly Inclusion" },
      { diamondType: ["SI1"], value: "SI1", desc: "Slightly Inclusion" },
      { diamondType: ["SI2"], value: "SI2", desc: "Slightly Inclusion" },
      { diamondType: ["I1"], value: "I1", desc: "Inclusion or Pique" },
      { diamondType: ["I2"], value: "I2", desc: "Inclusion or Pique" },
      { diamondType: ["I3"], value: "I3", desc: "Inclusion or Pique" },
    ],
  },
  {
    color: { img: "purplish-red", value: "Purplish Red" },
    shape: [
      { id: 1, img: "radient", value: "Radiant" },
      { id: 2, img: "cushion", value: "Cushion" },
      { id: 3, img: "oval", value: "Oval" },
      { id: 4, img: "heart", value: "Heart" },
      { id: 5, img: "pear", value: "Pear" },
      { id: 6, img: "emerald", value: "Emerald" },
      { id: 7, img: "round", value: "Round" },
      { id: 8, img: "marquise", value: "Marquise" },
    ],
    saturation: [
      "Fancy",
    ],
    clarity: [
      { diamondType: ["FL or IF"], value: "IF", desc: "Flawless/Internally…" },
      { diamondType: ["VVS"], value: "VVS", desc: "Very Very Slightly Incl…" },
      { diamondType: ["VS"], value: "VS", desc: "Very  Slightly Inclusion" },
      { diamondType: ["SI1"], value: "SI1", desc: "Slightly Inclusion" },
      { diamondType: ["SI2"], value: "SI2", desc: "Slightly Inclusion" },
      { diamondType: ["I1"], value: "I1", desc: "Inclusion or Pique" },
      { diamondType: ["I2"], value: "I2", desc: "Inclusion or Pique" },
      { diamondType: ["I3"], value: "I3", desc: "Inclusion or Pique" },
    ],
  },
  {
    color: { img: "brownish-red", value: "Brownish Red" },
    shape: [
      { id: 1, img: "radient", value: "Radiant" },
      { id: 2, img: "cushion", value: "Cushion" },
      { id: 3, img: "oval", value: "Oval" },
      { id: 4, img: "heart", value: "Heart" },
      { id: 5, img: "pear", value: "Pear" },
      { id: 6, img: "emerald", value: "Emerald" },
      { id: 7, img: "round", value: "Round" },
      { id: 8, img: "marquise", value: "Marquise" },
      { id: 9, img: "hexagon", value: "Hexagon" },
      { id: 10, img: "triangular-brilliant", value: "Triangular Brilliant" },
      { id: 11, img: "octagon", value: "Octagon" },
      { id: 12, img: "princess", value: "Princess" },
      { id: 13, img: "trilliant", value: "Trilliant" },
      { id: 14, img: "kite", value: "Kite" },
      { id: 15, img: "shield", value: "Shield" },
    ],
    saturation: [
      "Fancy",
    ],
    clarity: [
      { diamondType: ["FL or IF"], value: "IF", desc: "Flawless/Internally…" },
      { diamondType: ["VVS"], value: "VVS", desc: "Very Very Slightly Incl…" },
      { diamondType: ["VS"], value: "VS", desc: "Very  Slightly Inclusion" },
      { diamondType: ["SI1"], value: "SI1", desc: "Slightly Inclusion" },
      { diamondType: ["SI2"], value: "SI2", desc: "Slightly Inclusion" },
      { diamondType: ["I1"], value: "I1", desc: "Inclusion or Pique" },
      { diamondType: ["I2"], value: "I2", desc: "Inclusion or Pique" },
      { diamondType: ["I3"], value: "I3", desc: "Inclusion or Pique" },
    ],
  },
  {
    color: { img: "blue-grey", value: "Blue Gray" },
    shape: [
      { id: 1, img: "radient", value: "Radiant" },
      { id: 2, img: "cushion", value: "Cushion" },
      { id: 3, img: "oval", value: "Oval" },
      { id: 4, img: "heart", value: "Heart" },
      { id: 5, img: "pear", value: "Pear" },
      { id: 6, img: "emerald", value: "Emerald" },
      { id: 7, img: "round", value: "Round" },
      { id: 8, img: "marquise", value: "Marquise" },
      { id: 9, img: "hexagon", value: "Hexagon" },
      { id: 10, img: "triangular-brilliant", value: "Triangular Brilliant" },
      { id: 11, img: "octagon", value: "Octagon" },
      { id: 12, img: "princess", value: "Princess" },
      { id: 13, img: "trilliant", value: "Trilliant" },
      { id: 14, img: "kite", value: "Kite" },
      { id: 15, img: "shield", value: "Shield" },
    ],
    saturation: [
      
      "Fancy",
      "Fancy Intense",
      "Fancy Vivid",
      "Fancy Deep",
      "Fancy Dark",
    ],
    clarity: [
      { diamondType: ["FL or IF"], value: "IF", desc: "Flawless/Internally…" },
      { diamondType: ["VVS"], value: "VVS", desc: "Very Very Slightly Incl…" },
      { diamondType: ["VS"], value: "VS", desc: "Very  Slightly Inclusion" },
      { diamondType: ["SI1"], value: "SI1", desc: "Slightly Inclusion" },
      { diamondType: ["SI2"], value: "SI2", desc: "Slightly Inclusion" },
      { diamondType: ["I1"], value: "I1", desc: "Inclusion or Pique" },
      { diamondType: ["I2"], value: "I2", desc: "Inclusion or Pique" },
      { diamondType: ["I3"], value: "I3", desc: "Inclusion or Pique" },
    ],
  },
  {
    color: { img: "grey-blue", value: "Gray Blue" },
    shape: [
      { id: 1, img: "radient", value: "Radiant" },
      { id: 2, img: "cushion", value: "Cushion" },
      { id: 3, img: "oval", value: "Oval" },
      { id: 4, img: "heart", value: "Heart" },
      { id: 5, img: "pear", value: "Pear" },
      { id: 6, img: "emerald", value: "Emerald" },
      { id: 7, img: "round", value: "Round" },
      { id: 8, img: "marquise", value: "Marquise" },
      { id: 9, img: "hexagon", value: "Hexagon" },
      { id: 10, img: "triangular-brilliant", value: "Triangular Brilliant" },
      { id: 11, img: "octagon", value: "Octagon" },
      { id: 12, img: "princess", value: "Princess" },
      { id: 13, img: "trilliant", value: "Trilliant" },
      { id: 14, img: "kite", value: "Kite" },
      { id: 15, img: "shield", value: "Shield" },
    ],
    saturation: [
      
      "Fancy",
      "Fancy Intense",
      "Fancy Vivid",
      "Fancy Deep",
      "Fancy Dark",
    ],
    clarity: [
      { diamondType: ["FL or IF"], value: "IF", desc: "Flawless/Internally…" },
      { diamondType: ["VVS"], value: "VVS", desc: "Very Very Slightly Incl…" },
      { diamondType: ["VS"], value: "VS", desc: "Very  Slightly Inclusion" },
      { diamondType: ["SI1"], value: "SI1", desc: "Slightly Inclusion" },
      { diamondType: ["SI2"], value: "SI2", desc: "Slightly Inclusion" },
      { diamondType: ["I1"], value: "I1", desc: "Inclusion or Pique" },
      { diamondType: ["I2"], value: "I2", desc: "Inclusion or Pique" },
      { diamondType: ["I3"], value: "I3", desc: "Inclusion or Pique" },
    ],
  },
  {
    color: { img: "grey-violet", value: "Gray Violet" },
    shape: [
      { id: 1, img: "radient", value: "Radiant" },
      { id: 2, img: "cushion", value: "Cushion" },
      { id: 3, img: "oval", value: "Oval" },
      { id: 4, img: "heart", value: "Heart" },
      { id: 5, img: "pear", value: "Pear" },
      { id: 6, img: "emerald", value: "Emerald" },
      { id: 7, img: "round", value: "Round" },
      { id: 8, img: "marquise", value: "Marquise" },
      { id: 9, img: "hexagon", value: "Hexagon" },
      { id: 10, img: "triangular-brilliant", value: "Triangular Brilliant" },
      { id: 11, img: "octagon", value: "Octagon" },
      { id: 12, img: "princess", value: "Princess" },
      { id: 13, img: "trilliant", value: "Trilliant" },
      { id: 14, img: "kite", value: "Kite" },
      { id: 15, img: "shield", value: "Shield" },
    ],
    saturation: [
    
      "Fancy",
      "Fancy Intense",
      "Fancy Vivid",
      "Fancy Deep",
      "Fancy Dark",
    ],
    clarity: [
      { diamondType: ["FL or IF"], value: "IF", desc: "Flawless/Internally…" },
      { diamondType: ["VVS"], value: "VVS", desc: "Very Very Slightly Incl…" },
      { diamondType: ["VS"], value: "VS", desc: "Very  Slightly Inclusion" },
      { diamondType: ["SI1"], value: "SI1", desc: "Slightly Inclusion" },
      { diamondType: ["SI2"], value: "SI2", desc: "Slightly Inclusion" },
      { diamondType: ["I1"], value: "I1", desc: "Inclusion or Pique" },
      { diamondType: ["I2"], value: "I2", desc: "Inclusion or Pique" },
      { diamondType: ["I3"], value: "I3", desc: "Inclusion or Pique" },
    ],
  },
  {
    color: { img: "grayish-bluish-violet", value: "Grayish Bluish Violet" },
    shape: [
      { id: 1, img: "radient", value: "Radiant" },
      { id: 2, img: "cushion", value: "Cushion" },
      { id: 3, img: "oval", value: "Oval" },
      { id: 4, img: "heart", value: "Heart" },
      { id: 5, img: "pear", value: "Pear" },
      { id: 6, img: "emerald", value: "Emerald" },
      { id: 7, img: "round", value: "Round" },
      { id: 8, img: "marquise", value: "Marquise" },
      { id: 9, img: "hexagon", value: "Hexagon" },
      { id: 10, img: "triangular-brilliant", value: "Triangular Brilliant" },
      { id: 11, img: "octagon", value: "Octagon" },
      { id: 12, img: "princess", value: "Princess" },
      { id: 13, img: "trilliant", value: "Trilliant" },
      { id: 14, img: "kite", value: "Kite" },
      { id: 15, img: "shield", value: "Shield" },
    ],
    saturation: [
      
      "Fancy",
      "Fancy Intense",
      "Fancy Vivid",
      "Fancy Deep",
      "Fancy Dark",
    ],
    clarity: [
      { diamondType: ["FL or IF"], value: "IF", desc: "Flawless/Internally…" },
      { diamondType: ["VVS"], value: "VVS", desc: "Very Very Slightly Incl…" },
      { diamondType: ["VS"], value: "VS", desc: "Very  Slightly Inclusion" },
      { diamondType: ["SI1"], value: "SI1", desc: "Slightly Inclusion" },
      { diamondType: ["SI2"], value: "SI2", desc: "Slightly Inclusion" },
      { diamondType: ["I1"], value: "I1", desc: "Inclusion or Pique" },
      { diamondType: ["I2"], value: "I2", desc: "Inclusion or Pique" },
      { diamondType: ["I3"], value: "I3", desc: "Inclusion or Pique" },
    ],
  },
  {
    color: { img: "grayish-violetish-blue", value: "Grayish Violetish Blue" },
    shape: [
      { id: 1, img: "radient", value: "Radiant" },
      { id: 2, img: "cushion", value: "Cushion" },
      { id: 3, img: "oval", value: "Oval" },
      { id: 4, img: "heart", value: "Heart" },
      { id: 5, img: "pear", value: "Pear" },
      { id: 6, img: "emerald", value: "Emerald" },
      { id: 7, img: "round", value: "Round" },
      { id: 8, img: "marquise", value: "Marquise" },
      { id: 9, img: "hexagon", value: "Hexagon" },
      { id: 10, img: "triangular-brilliant", value: "Triangular Brilliant" },
      { id: 11, img: "octagon", value: "Octagon" },
      { id: 12, img: "princess", value: "Princess" },
      { id: 13, img: "trilliant", value: "Trilliant" },
      { id: 14, img: "kite", value: "Kite" },
      { id: 15, img: "shield", value: "Shield" },
    ],
    saturation: [
     
      "Fancy",
      "Fancy Intense",
      "Fancy Vivid",
      "Fancy Deep",
      "Fancy Dark",
    ],
    clarity: [
      { diamondType: ["FL or IF"], value: "IF", desc: "Flawless/Internally…" },
      { diamondType: ["VVS"], value: "VVS", desc: "Very Very Slightly Incl…" },
      { diamondType: ["VS"], value: "VS", desc: "Very  Slightly Inclusion" },
      { diamondType: ["SI1"], value: "SI1", desc: "Slightly Inclusion" },
      { diamondType: ["SI2"], value: "SI2", desc: "Slightly Inclusion" },
      { diamondType: ["I1"], value: "I1", desc: "Inclusion or Pique" },
      { diamondType: ["I2"], value: "I2", desc: "Inclusion or Pique" },
      { diamondType: ["I3"], value: "I3", desc: "Inclusion or Pique" },
    ],
  },
  {
    color: { img: "violet-grey", value: "Violet Gray" },
    shape: [
      { id: 1, img: "radient", value: "Radiant" },
      { id: 2, img: "cushion", value: "Cushion" },
      { id: 3, img: "oval", value: "Oval" },
      { id: 4, img: "heart", value: "Heart" },
      { id: 5, img: "pear", value: "Pear" },
      { id: 6, img: "emerald", value: "Emerald" },
      { id: 7, img: "round", value: "Round" },
      { id: 8, img: "marquise", value: "Marquise" },
      { id: 9, img: "hexagon", value: "Hexagon" },
      { id: 10, img: "triangular-brilliant", value: "Triangular Brilliant" },
      { id: 11, img: "octagon", value: "Octagon" },
      { id: 12, img: "princess", value: "Princess" },
      { id: 13, img: "trilliant", value: "Trilliant" },
      { id: 14, img: "kite", value: "Kite" },
      { id: 15, img: "shield", value: "Shield" },
    ],
    saturation: [
     
      "Fancy",
      "Fancy Intense",
      "Fancy Vivid",
      "Fancy Deep",
      "Fancy Dark",
    ],
    clarity: [
      { diamondType: ["FL or IF"], value: "IF", desc: "Flawless/Internally…" },
      { diamondType: ["VVS"], value: "VVS", desc: "Very Very Slightly Incl…" },
      { diamondType: ["VS"], value: "VS", desc: "Very  Slightly Inclusion" },
      { diamondType: ["SI1"], value: "SI1", desc: "Slightly Inclusion" },
      { diamondType: ["SI2"], value: "SI2", desc: "Slightly Inclusion" },
      { diamondType: ["I1"], value: "I1", desc: "Inclusion or Pique" },
      { diamondType: ["I2"], value: "I2", desc: "Inclusion or Pique" },
      { diamondType: ["I3"], value: "I3", desc: "Inclusion or Pique" },
    ],
  },
  {
    color: { img: "violetish-grey", value: "Violetish Gray" },
    shape: [
      { id: 1, img: "radient", value: "Radiant" },
      { id: 2, img: "cushion", value: "Cushion" },
      { id: 3, img: "oval", value: "Oval" },
      { id: 4, img: "heart", value: "Heart" },
      { id: 5, img: "pear", value: "Pear" },
      { id: 6, img: "emerald", value: "Emerald" },
      { id: 7, img: "round", value: "Round" },
      { id: 8, img: "marquise", value: "Marquise" },
      { id: 9, img: "hexagon", value: "Hexagon" },
      { id: 10, img: "triangular-brilliant", value: "Triangular Brilliant" },
      { id: 11, img: "octagon", value: "Octagon" },
      { id: 12, img: "princess", value: "Princess" },
      { id: 13, img: "trilliant", value: "Trilliant" },
      { id: 14, img: "kite", value: "Kite" },
      { id: 15, img: "shield", value: "Shield" },
    ],
    saturation: [
      
      "Fancy",
      "Fancy Intense",
      "Fancy Vivid",
      "Fancy Deep",
      "Fancy Dark",
    ],
    clarity: [
      { diamondType: ["FL or IF"], value: "IF", desc: "Flawless/Internally…" },
      { diamondType: ["VVS"], value: "VVS", desc: "Very Very Slightly Incl…" },
      { diamondType: ["VS"], value: "VS", desc: "Very  Slightly Inclusion" },
      { diamondType: ["SI1"], value: "SI1", desc: "Slightly Inclusion" },
      { diamondType: ["SI2"], value: "SI2", desc: "Slightly Inclusion" },
      { diamondType: ["I1"], value: "I1", desc: "Inclusion or Pique" },
      { diamondType: ["I2"], value: "I2", desc: "Inclusion or Pique" },
      { diamondType: ["I3"], value: "I3", desc: "Inclusion or Pique" },
    ],
  },
  {
    color: { img: "greyish-violet", value: "Grayish Violet" },
    shape: [
      { id: 1, img: "radient", value: "Radiant" },
      { id: 2, img: "cushion", value: "Cushion" },
      { id: 3, img: "oval", value: "Oval" },
      { id: 4, img: "heart", value: "Heart" },
      { id: 5, img: "pear", value: "Pear" },
      { id: 6, img: "emerald", value: "Emerald" },
      { id: 7, img: "round", value: "Round" },
      { id: 8, img: "marquise", value: "Marquise" },
      { id: 9, img: "hexagon", value: "Hexagon" },
      { id: 10, img: "triangular-brilliant", value: "Triangular Brilliant" },
      { id: 11, img: "octagon", value: "Octagon" },
      { id: 12, img: "princess", value: "Princess" },
      { id: 13, img: "trilliant", value: "Trilliant" },
      { id: 14, img: "kite", value: "Kite" },
      { id: 15, img: "shield", value: "Shield" },
    ],
    saturation: [
     
      "Fancy",
      "Fancy Intense",
      "Fancy Vivid",
      "Fancy Deep",
      "Fancy Dark",
    ],
    clarity: [
      { diamondType: ["FL or IF"], value: "IF", desc: "Flawless/Internally…" },
      { diamondType: ["VVS"], value: "VVS", desc: "Very Very Slightly Incl…" },
      { diamondType: ["VS"], value: "VS", desc: "Very  Slightly Inclusion" },
      { diamondType: ["SI1"], value: "SI1", desc: "Slightly Inclusion" },
      { diamondType: ["SI2"], value: "SI2", desc: "Slightly Inclusion" },
      { diamondType: ["I1"], value: "I1", desc: "Inclusion or Pique" },
      { diamondType: ["I2"], value: "I2", desc: "Inclusion or Pique" },
      { diamondType: ["I3"], value: "I3", desc: "Inclusion or Pique" },
    ],
  },
  {
    color: { img: "orangy-pink", value: "Orangy Pink" },
    shape: [
      { id: 1, img: "radient", value: "Radiant" },
      { id: 2, img: "cushion", value: "Cushion" },
      { id: 3, img: "oval", value: "Oval" },
      { id: 4, img: "heart", value: "Heart" },
      { id: 5, img: "pear", value: "Pear" },
      { id: 6, img: "emerald", value: "Emerald" },
      { id: 7, img: "round", value: "Round" },
      { id: 8, img: "marquise", value: "Marquise" },
      { id: 9, img: "hexagon", value: "Hexagon" },
      { id: 10, img: "triangular-brilliant", value: "Triangular Brilliant" },
      { id: 11, img: "octagon", value: "Octagon" },
      { id: 12, img: "princess", value: "Princess" },
      { id: 13, img: "trilliant", value: "Trilliant" },
      { id: 14, img: "kite", value: "Kite" },
      { id: 15, img: "shield", value: "Shield" },
    ],
    saturation: [
    
      "Fancy",
      "Fancy Intense",
      "Fancy Vivid",
      "Fancy Deep",
      "Fancy Dark",
    ],
    clarity: [
      { diamondType: ["FL or IF"], value: "IF", desc: "Flawless/Internally…" },
      { diamondType: ["VVS"], value: "VVS", desc: "Very Very Slightly Incl…" },
      { diamondType: ["VS"], value: "VS", desc: "Very  Slightly Inclusion" },
      { diamondType: ["SI1"], value: "SI1", desc: "Slightly Inclusion" },
      { diamondType: ["SI2"], value: "SI2", desc: "Slightly Inclusion" },
      { diamondType: ["I1"], value: "I1", desc: "Inclusion or Pique" },
      { diamondType: ["I2"], value: "I2", desc: "Inclusion or Pique" },
      { diamondType: ["I3"], value: "I3", desc: "Inclusion or Pique" },
    ],
  },
 
];




