import { CauseShape } from '../../types/shape.types';

export const DiaryCauseShape: CauseShape[] = [
  { code: 'HX', shape: 'Heart' },
  { code: 'CB', shape: 'Cushion / Radiant' },
  { code: 'CCSB', shape: 'Cushion / Radiant' },
  { code: 'CIRC', shape: 'Round' },
  { code: 'CMB', shape: 'Cushion / Radiant' },
  { code: 'CRB', shape: 'Cushion / Radiant' },
  { code: 'CRMB', shape: 'Cushion / Radiant' },
  { code: 'CRSC', shape: 'Emerald' },
  { code: 'CRX', shape: 'Cushion / Radiant' },
  { code: 'CSMB', shape: 'Cushion / Radiant' },
  { code: 'CSSC', shape: 'Emerald' },
  { code: 'CSX', shape: 'Cushion / Radiant' },
  { code: 'CX', shape: 'Cushion / Radiant' },
  { code: 'EM', shape: 'Emerald' },
  { code: 'HB', shape: 'Heart' },
  { code: 'HMB', shape: 'Heart' },
  { code: 'MHB', shape: 'Heart' },
  { code: 'MHX', shape: 'Heart' },
  { code: 'MMB', shape: 'Marquise' },
  { code: 'MOB', shape: 'Oval' },
  { code: 'MOX', shape: 'Oval' },
  { code: 'MPX', shape: 'Pear' },
  { code: 'MMC', shape: 'Marquise' },
  { code: 'MMX', shape: 'Marquise' },
  { code: 'OB', shape: 'Oval' },
  { code: 'PB', shape: 'Pear' },
  { code: 'PMB', shape: 'Pear' },
  { code: 'RCRB', shape: 'Cushion / Radiant' },
  { code: 'RCSB', shape: 'Cushion / Radiant' },
  { code: 'RCSMB', shape: 'Cushion / Radiant' },
  { code: 'SEM', shape: 'Emerald' },
  { code: 'OMB', shape: 'Oval' },
  { code: 'RBC', shape: 'Round' },
  { code: 'RCRMB', shape: 'Cushion / Radiant' },
  { code: 'RCSX', shape: 'Cushion / Radiant' },
  { code: 'RCSSC', shape: 'Cushion / Radiant' },
  { code: 'PX', shape: 'Pear' },
  { code: 'OX', shape: 'Oval' },
  { code: 'MPB', shape: 'Pear' },
  { code: 'RMB', shape: 'Round' },
  { code: 'RCRX', shape: 'Cushion / Radiant' },
  { code: 'OEB', shape: 'Round' },
  { code: 'MRB', shape: 'Cushion / Radiant' },
  { code: 'OSC', shape: 'Oval' },
];

export default DiaryCauseShape;