import { DiamondColor } from '../../types/color.types';

export const DiamondColors: DiamondColor[] = [
  { id: 1, img: 'yellow', name: 'Yellow', value: 'Yellow' },
  {
    id: 2,
    img: 'greenish-yellow',
    name: 'Green/ish Yellow',
    value: 'Greenish Yellow',
  },
  {
    id: 3,
    img: 'orange-yellow',
    name: 'Orange Yellow',
    value: 'Orange Yellow',
  },
  {
    id: 3,
    img: 'orangy-yellow',
    name: 'Orangy Yellow',
    value: 'Orangy Yellow',
  },
  {
    id: 4,
    img: 'pink',
    name: 'Pink/Purple/ish Pink',
    value: 'Pink - Purplish Pink',
  },
  {
    id: 4,
    img: 'pink',
    name: 'Pink/Purple/ish Pink',
    value: 'Pink',
  },
  {
    id: 4,
    img: 'pink',
    name: 'Pink/Purple/ish Pink',
    value: 'Purplish Pink',
  },
  { id: 5, img: 'orangy-pink', name: 'Orangy Pink', value: 'Orangy Pink' },
  {
    id: 7,
    img: 'pinkish-purple',
    name: 'Pink/ish Purple',
    value: 'Pinkish Purple',
  },
  { id: 8, img: 'purple', name: 'Purple', value: 'Purple' },
  {
    id: 9,
    img: 'brownish-pink',
    name: 'Brownish Pink',
    value: 'Brownish Pink',
  },
  { id: 10, img: 'brown-pink', name: 'Brown Pink', value: 'Brown Pink' },
  { id: 11, img: 'blue', name: 'Blue', value: 'Blue' },
  { id: 12, img: 'grey-blue', name: 'Gray Blue', value: 'Gray Blue' },
  { id: 13, img: 'green-blue', name: 'Green Blue', value: 'Green Blue' },
  {
    id: 13,
    img: 'greenish-blue',
    name: 'Greenish Blue',
    value: 'Greenish Blue',
  },
  { id: 14, img: 'grayish-blue', name: 'Grayish Blue', value: 'Grayish Blue' },
  { id: 15, img: 'orange', name: 'Orange', value: 'Orange' },
  {
    id: 16,
    img: 'yellow-orange',
    name: 'Yellow Orange',
    value: 'Yellow Orange',
  },
  {
    id: 17,
    img: 'yellowish-orange',
    name: 'Yellowish Orange',
    value: 'Yellowish Orange',
  },
  { id: 18, img: 'brown-orange', name: 'Brown Orange', value: 'Brown Orange' },
  { id: 19, img: 'green', name: 'Green', value: 'Green' },
  {
    id: 20,
    img: 'yellow-green',
    name: 'Yellow/ish Green',
    value: 'Yellow Green',
  },
  {
    id: 20,
    img: 'yellow-green',
    name: 'Yellow/ish Green',
    value: 'Yellowish Green',
  },
  {
    id: 20,
    img: 'yellow-green',
    name: 'Green/ish Yellow',
    value: 'Green Yellow',
  },
  {
    id: 21,
    img: 'bluegreen',
    name: 'Blue Green',
    value: 'Blue Green',
  },
  {
    id: 22,
    img: 'bluish-green',
    name: 'Bluish Green',
    value: 'Bluish Green',
  },
  { id: 23, img: 'red', name: 'Red', value: 'Red' },
  { id: 24, img: 'purplish-red', name: 'Purplish Red', value: 'Purplish Red' },
  { id: 25, img: 'grey', name: 'Gray', value: 'Gray' },
  { id: 26, img: 'blue-grey', name: 'Blue/ish Gray', value: 'Blue Gray' },
  {
    id: 27,
    img: 'bluegreen',
    name: 'Blue/ish Gray',
    value: 'Blueish Gray',
  },
  {
    id: 28,
    img: 'bluegreen',
    name: 'Blue/ish Gray',
    value: 'Bluish Gray',
  },
  {
    id: 30,
    img: 'pink',
    name: 'Pink/Purple/ish Pink',
    value: 'Purple Pink',
  },
  {
    id: 30,
    img: 'Pinkish-Purple',
    name: 'Pink/ish Purple',
    value: 'Pinkish Purple',
  },
  {
    id: 30,
    img: 'Pinkish-Purple',
    name: 'Pink/ish Purple',
    value: 'Pink Purple',
  },
  {
    id: 30,
    img: 'Pinkish-Purple',
    name: 'Pink/ish Purple',
    value: 'Pink Purple',
  },
  {
    id: 30,
    img: 'Pinkish-Purple',
    name: 'Pink/ish Purple',
    value: 'Pinkish-Purple',
  },
  {
    id: 30,
    img: 'Pinkish-Purple',
    name: 'Pink/ish Purple',
    value: 'Pink-Purple',
  },
  {
    id: 31,
    img: 'brownish-orange',
    name: 'Brownish Orange',
    value: 'Brownish Orange',
  },
  {
    id: 32,
    img: 'gray-violet',
    name: 'Gray/ish Violet',
    value: 'Grayish Violet',
  },
  {
    id: 32,
    img: 'gray-violet',
    name: 'Gray/ish Violet',
    value: 'Gray Violet',
  },
  {
    id: 33,
    img: 'brownish-yellowish-orange',
    name: 'Brownish Yellowish Orange',
    value: 'Brownish Yellowish Orange',
  },
  {
    id: 33,
    img: 'brownish-orangy-pink',
    name: 'Brownish Orange/y Pink',
    value: 'Brownish Orangy Pink',
  },
  {
    id: 33,
    img: 'brownish-orangy-pink',
    name: 'Brownish Orange/y Pink',
    value: 'Brownish Orange Pink',
  },
  {
    id: 33,
    img: 'brownish-orangy-pink',
    name: 'Brownish Orange/y Pink',
    value: 'Brownish Orange/y Pink',
  },
  {
    id: 35,
    img: 'pinkish-orange',
    name: 'Pink/ish Orange',
    value: 'Pinkish Orange',
  },
  {
    id: 35,
    img: 'pinkish-orange',
    name: 'Pink/ish Orange',
    value: 'Pink Orange',
  },
  {
    id: 35,
    img: 'brownish-yellow',
    name: 'Brown/ish Yellow',
    value: 'Brown/ish Yellow',
  },
  {
    id: 35,
    img: 'brownish-yellow',
    name: 'Brown/ish Yellow',
    value: 'Brown Yellow',
  }
];

export default DiamondColors;