import { DiaryDiamondColor } from '../../types/color.types';

export const DiaryDiamondColors: DiaryDiamondColor[] = [
  { id: 1, img: 'yellow', name: 'Yellow', value: 'Yellow' },
  {
    id: 2,
    img: 'greenish-yellow',
    name: 'Greenish Yellow',
    value: 'Greenish Yellow',
  },
  {
    id: 2,
    img: 'greenish-yellow',
    name: 'Greenish Yellow',
    value: 'Green Yellow',
  },
  {
    id: 3,
    img: 'orange-yellow',
    name: 'Orange Yellow',
    value: 'Orange Yellow',
  },
  {
    id: 4,
    img: 'pink',
    name: 'Pink',
    value: 'Pink',
  },
  { id: 5, img: 'orangy-pink', name: 'Orangy Pink', value: 'Orangy Pink' },
  {
    id: 6,
    img: 'purplish-pink',
    name: 'Purplish Pink',
    value: 'Purplish Pink',
  },
  {
    id: 7,
    img: 'pinkish-purple',
    name: 'Pink/ish Purple',
    value: 'Pink/ish Purple',
  },
  { id: 8, img: 'purple', name: 'Purple', value: 'Purple' },
  { id: 8, img: 'pink', name: 'Purple Pink', value: 'Purple Pink' },
  {
    id: 9,
    img: 'brownish-pink',
    name: 'Brownish Pink',
    value: 'Brownish Pink',
  },
  { id: 10, img: 'brown-pink', name: 'Brown Pink', value: 'Brown Pink' },
  { id: 11, img: 'blue', name: 'Blue', value: 'Blue' },
  { id: 12, img: 'grey-blue', name: 'Gray Blue', value: 'Gray Blue' },
  { id: 13, img: 'green-blue', name: 'Green Blue', value: 'Green Blue' },
  {
    id: 14,
    img: 'greenish-blue',
    name: 'Greenish Blue',
    value: 'Greenish Blue',
  },
  { id: 15, img: 'grayish-blue', name: 'Grayish Blue', value: 'Grayish Blue' },
  { id: 16, img: 'orange', name: 'Orange', value: 'Orange' },
  {
    id: 17,
    img: 'yellow-orange',
    name: 'Yellow Orange',
    value: 'Yellow Orange',
  },
  {
    id: 18,
    img: 'yellowish-orange',
    name: 'Yellowish Orange',
    value: 'Yellowish Orange',
  },
  { id: 19, img: 'brown-orange', name: 'Brown Orange', value: 'Brown Orange' },
  { id: 20, img: 'green', name: 'Green', value: 'Green' },
  {
    id: 21,
    img: 'yellow-green',
    name: 'Yellow Green',
    value: 'Yellow Green',
  },
  {
    id: 22,
    img: 'bluegreen',
    name: 'Blue Green',
    value: 'Blue Green',
  },
  {
    id: 23,
    img: 'bluish-green',
    name: 'Bluish Green',
    value: 'Bluish Green',
  },
  { id: 24, img: 'red', name: 'Red', value: 'Red' },
  { id: 25, img: 'purplish-red', name: 'Purplish Red', value: 'Purplish Red' },
  { id: 26, img: 'grey', name: 'Gray', value: 'Gray' },
  { id: 27, img: 'blue-grey', name: 'Blue Gray', value: 'Blue Gray' },
  { id: 27, img: 'purple-brown-grey', name: 'Purple with Brown or Gray', value: 'Purple with Brown or Gray' },
  { id: 28, img: 'grey-violet', name: 'Gray-violet - violet gray', value: 'Gray-violet - violet gray' },
  { id: 29, img: 'violet-blue', name: 'Violet-blue to blue violet', value: 'Violet-blue to blue violet' },
  { id: 30, img: 'violet', name: 'Violet', value: 'Violet' },
  { id: 31, img: 'greyish-yellow-green', name: 'Grayish yellow-green', value: 'Grayish yellow-green' },
  {
    id: 32,
    img: 'brownish-greenish-yellow',
    name: 'Brownish greenish yellow',
    value: 'Brownish greenish yellow',
  },
  { id: 33, img: 'greyish-green-yellow', name: 'Grayish green-yellow', value: 'Grayish green-yellow' },
  { id: 34, img: 'green-grey', name: 'Green gray to gray green', value: 'Green gray to gray green' },
  {
    id: 35,
    img: 'greenish-yellow',
    name: 'Green/ish Yellow',
    value: 'Green/ish Yellow',
  },
  {
    id: 36,
    img: 'purplish-pink',
    name: 'Purple/ish Pink',
    value: 'Purple/ish Pink',
  },
  {
    id: 37,
    img: 'purplish-pink',
    name: 'Pink - Purplish Pink',
    value: 'Pink - Purplish Pink',
  },
  {
    id: 38,
    img: 'yellow-green',
    name: 'Yellow/ish Green',
    value: 'Yellow/ish Green',
  },
  { id: 39, img: 'blue-grey', name: 'Blue/ish Gray', value: 'Blue/ish Gray' },
  {
    id: 40,
    img: 'pink',
    name: 'Pink/Purple/ish Pink',
    value: 'Pink/Purple/ish Pink',
  },
  {
    id: 41,
    img: 'orangy-yellow',
    name: 'Orangy Yellow',
    value: 'Orangy Yellow',
  },
  {
    id: 42,
    img: 'pink',
    name: 'Pink/ish Purple',
    value: 'Pink/ish Purple',
  },
  {
    id: 43,
    img: 'brownish-orange',
    name: 'Brownish Orange',
    value: 'Brownish Orange',
  },
  {
    id: 44,
    img: "gray-violet",
    name: "Gray/ish Violet",
    value: "Gray Violet",
  },
   {
    id: 44,
    img: "gray-violet",
    name: "Gray/ish Violet",
    value: "Grayish Violet",
  },
   {
    id: 45,
    img: "brownish-yellowish-orange",
    name: "Brownish Yellowish Orange",
    value: "Brownish Yellowish Orange",
  }
];

export default DiaryDiamondColors;